@echo off
echo Installing Python dependencies for OCR...
echo Installing uv...
powershell -Command "iwr -useb https://astral.sh/uv/install.ps1 | iex"
echo Using uv to install markitdown...
uv sync
echo Finished installing Python dependencies