name: CI

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: oven-sh/setup-bun@v2

      - run: bun install

      - run: bun run lint

      - run: bun run build

      - run: bun test
